name = "DateWithNovels SiteAdmin"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "task2"
  title = "This is a bug should be repair"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ "/middleware.ts" ]
  dueDate = ""
  priority = ""
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "tlvneo7ja1o1r5s9or36ruhi"
    title = "sdknc;lskdc"
    completed = true

    [[processes.tasks.checkList]]
    id = "ylcv2kayz08njog4q73mr0zg"
    title = "sdcdsacs"
    completed = false

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "auze9mvpavri301e82plj03g"
  title = "Test"
  description = "Test 2"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "rzbmhz2oeh93lu5kmc01t38f"
  title = "Hellow"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "w3l7rrrakvwegvafzkwzc02o"
  title = "Hello"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "task1"
  title = "This is a new feature"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
